repos:
- repo: local
  hooks:
    - id: pytest
      name: Run tests
      entry: pytest tests/test.py
      language: system
      types: [python]
      pass_filenames: false
      always_run: true
- repo: https://github.com/astral-sh/ruff-pre-commit
  # Ruff version.
  rev: v0.7.1
  hooks:
    # Run the linter.
    - id: ruff
      types_or: [ python, pyi ]
      args: [ --fix ]
    # Run the formatter.
    - id: ruff-format
      types_or: [ python, pyi ]